name: CMake

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  TEST_JOBS: 30

jobs:
  check-format:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check code formatting
        run: |
          find . -regex '.*\.\(cpp\|hpp\|cc\|hh\|cxx\|h\)' -exec clang-format -style=file -i {} \;
          git diff --exit-code
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: ${{ matrix.os }} ${{ matrix.generator }} ${{ matrix.compiler }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    needs: check-format
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        compiler: [g++, clang++]
        generator: [Unix Makefiles, Ninja]
        build_type: [Debug, Release]

    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v3

      - name: Install Ninja
        if: ${{ matrix.generator == 'Ninja' }}
        run: sudo apt install ninja-build

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: |
          cmake -B ${{github.workspace}}/build \
            -G="${{matrix.generator}}" \
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} -j

      - name: Unit tests
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{matrix.build_type}} -j ${{env.TEST_JOBS}} -L unit
